services:
  - type: web
    name: iitm-mun-server
    runtime: node
    region: singapore  # closest to India
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: NOTIFY_EMAIL
        sync: false
